#!/bin/bash

if [ $# != 1 ]; then
    echo "Missing directory name."
    exit 1
fi

if [ ! -d $1 ]; then
    echo "The specified path is not a directory."
    exit 2
fi

find $1 -maxdepth 1 -type f
exit 0